/**
 * Answer word list for the daily word round (English, 5 letters).
 * Curated common words — every answer should feel fair to guess.
 * Guesses are validated as "any 5 alphabetic letters" for the MVP;
 * a full guess dictionary is a later refinement.
 */
export const ANSWERS = [
  'about', 'above', 'actor', 'acute', 'admit', 'adopt', 'after', 'again', 'agent', 'agree',
  'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone', 'along', 'alter',
  'amber', 'angel', 'anger', 'angle', 'ankle', 'apart', 'apple', 'apply', 'arena', 'argue',
  'arise', 'armor', 'aroma', 'array', 'arrow', 'aside', 'asset', 'atlas', 'audio', 'avoid',
  'awake', 'award', 'aware', 'badge', 'baker', 'basic', 'basin', 'beach', 'beard', 'beast',
  'begin', 'being', 'belly', 'below', 'bench', 'berry', 'birth', 'black', 'blade', 'blame',
  'blank', 'blast', 'blaze', 'blend', 'bless', 'blind', 'block', 'blood', 'bloom', 'board',
  'boast', 'bonus', 'boost', 'booth', 'bound', 'brain', 'brake', 'brand', 'brave', 'bread',
  'break', 'breed', 'brick', 'bride', 'brief', 'bring', 'broad', 'brook', 'broom', 'brown',
  'brush', 'build', 'bunch', 'burst', 'buyer', 'cabin', 'cable', 'candy', 'cargo', 'carry',
  'catch', 'cause', 'cease', 'chain', 'chair', 'chalk', 'charm', 'chart', 'chase', 'cheap',
  'check', 'cheek', 'cheer', 'chest', 'chief', 'child', 'chill', 'choir', 'chose', 'civic',
  'civil', 'claim', 'clash', 'class', 'clean', 'clear', 'clerk', 'click', 'cliff', 'climb',
  'clock', 'close', 'cloth', 'cloud', 'coach', 'coast', 'color', 'comet', 'coral', 'couch',
  'count', 'court', 'cover', 'crack', 'craft', 'crane', 'crash', 'cream', 'crest', 'crime',
  'crisp', 'cross', 'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crush', 'curve', 'cycle',
  'daily', 'dairy', 'dance', 'debut', 'delay', 'delta', 'dense', 'depth', 'devil', 'diary',
  'dirty', 'donor', 'doubt', 'dozen', 'draft', 'drain', 'drama', 'dream', 'dress', 'drift',
  'drill', 'drink', 'drive', 'drone', 'dwell', 'eager', 'eagle', 'early', 'earth', 'eight',
  'elbow', 'elder', 'elect', 'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal',
  'error', 'essay', 'event', 'every', 'exact', 'exile', 'exist', 'extra', 'fable', 'faint',
  'fairy', 'faith', 'false', 'fancy', 'fatal', 'fault', 'favor', 'feast', 'fence', 'fever',
  'fiber', 'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'flame', 'flash', 'fleet',
  'flesh', 'float', 'flock', 'flood', 'floor', 'flour', 'fluid', 'flute', 'focus', 'force',
  'forge', 'forth', 'forum', 'found', 'frame', 'fraud', 'fresh', 'front', 'frost', 'fruit',
  'fully', 'funny', 'ghost', 'giant', 'given', 'glass', 'globe', 'glory', 'glove', 'grace',
  'grade', 'grain', 'grand', 'grant', 'grape', 'grasp', 'grass', 'grave', 'great', 'green',
  'greet', 'grief', 'grill', 'group', 'grove', 'guard', 'guess', 'guest', 'guide', 'habit',
  'happy', 'harsh', 'haste', 'heart', 'heavy', 'hello', 'hence', 'hobby', 'honey', 'honor',
  'horse', 'hotel', 'house', 'human', 'humor', 'hurry', 'ideal', 'image', 'imply', 'index',
  'inner', 'input', 'irony', 'issue', 'ivory', 'jelly', 'jewel', 'joint', 'judge', 'juice',
  'knife', 'knock', 'known', 'label', 'labor', 'large', 'laser', 'later', 'laugh', 'layer',
  'learn', 'lease', 'least', 'leave', 'legal', 'lemon', 'level', 'light', 'limit', 'linen',
  'liver', 'lobby', 'local', 'logic', 'loose', 'lower', 'loyal', 'lucky', 'lunar', 'lunch',
  'magic', 'major', 'maker', 'maple', 'march', 'marsh', 'match', 'mayor', 'meant', 'medal',
  'media', 'melon', 'mercy', 'merge', 'merit', 'merry', 'metal', 'meter', 'midst', 'might',
  'minor', 'minus', 'mixed', 'model', 'money', 'month', 'moral', 'motor', 'mount', 'mouse',
  'mouth', 'movie', 'music', 'naval', 'nerve', 'never', 'night', 'noble', 'noise', 'north',
  'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often', 'olive', 'onion', 'opera',
  'orbit', 'order', 'organ', 'other', 'ought', 'ounce', 'outer', 'owner', 'oxide', 'ozone',
  'paint', 'panel', 'panic', 'paper', 'party', 'pasta', 'patch', 'pause', 'peace', 'pearl',
  'penny', 'petal', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch', 'pizza',
  'place', 'plain', 'plane', 'plant', 'plate', 'plaza', 'point', 'polar', 'pound', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove',
  'pulse', 'pupil', 'queen', 'query', 'quest', 'quick', 'quiet', 'quilt', 'quite', 'quote',
  'radar', 'radio', 'raise', 'rally', 'ranch', 'range', 'rapid', 'ratio', 'reach', 'ready',
  'realm', 'rebel', 'refer', 'reign', 'relax', 'reply', 'rider', 'ridge', 'rifle', 'right',
  'rigid', 'risky', 'rival', 'river', 'robot', 'rocky', 'rough', 'round', 'route', 'royal',
  'rural', 'salad', 'sauce', 'scale', 'scene', 'scent', 'scope', 'score', 'scout', 'sense',
  'serve', 'seven', 'shade', 'shaft', 'shake', 'shall', 'shame', 'shape', 'share', 'sharp',
  'sheep', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shore', 'short',
  'shout', 'sight', 'silly', 'since', 'sixth', 'skill', 'skirt', 'slate', 'sleep', 'slice',
  'slide', 'slope', 'small', 'smart', 'smile', 'smoke', 'snake', 'solar', 'solid', 'solve',
  'sonic', 'sorry', 'sound', 'south', 'space', 'spare', 'spark', 'speak', 'speed', 'spell',
  'spend', 'spice', 'spike', 'spine', 'spite', 'split', 'sport', 'spray', 'squad', 'stack',
  'staff', 'stage', 'stain', 'stair', 'stake', 'stand', 'stare', 'start', 'state', 'steam',
  'steel', 'steep', 'steer', 'stick', 'stiff', 'still', 'stock', 'stone', 'stood', 'store',
  'storm', 'story', 'stove', 'strap', 'straw', 'strip', 'stuck', 'study', 'stuff', 'style',
  'sugar', 'suite', 'sunny', 'super', 'surge', 'swamp', 'swear', 'sweet', 'swift', 'swing',
  'sword', 'table', 'taken', 'taste', 'teach', 'teeth', 'tempo', 'tenth', 'thank', 'theft',
  'theme', 'there', 'thick', 'thing', 'think', 'third', 'thorn', 'those', 'three', 'throw',
  'thumb', 'tiger', 'tight', 'timer', 'title', 'toast', 'today', 'token', 'topic', 'torch',
  'total', 'touch', 'tough', 'tower', 'trace', 'track', 'trade', 'trail', 'train', 'trait',
  'trash', 'treat', 'trend', 'trial', 'tribe', 'trick', 'troop', 'truck', 'truly', 'trunk',
  'trust', 'truth', 'tulip', 'twice', 'twist', 'ultra', 'uncle', 'under', 'union', 'unite',
  'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value', 'vapor',
  'vault', 'venue', 'verse', 'video', 'vigor', 'villa', 'vinyl', 'virus', 'visit', 'vital',
  'vivid', 'vocal', 'voice', 'voter', 'wagon', 'waist', 'waste', 'watch', 'water', 'weary',
  'weigh', 'weird', 'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole',
  'width', 'windy', 'wiser', 'witch', 'woman', 'world', 'worry', 'worse', 'worth', 'wound',
  'woven', 'wrist', 'write', 'wrong', 'wrote', 'yield', 'young', 'youth', 'zebra',
];

/** Pick a cryptographically random answer. */
export function pickAnswer() {
  const crypto = globalThis.crypto;
  const idx = crypto.getRandomValues(new Uint32Array(1))[0] % ANSWERS.length;
  return ANSWERS[idx];
}
